### ISSUE TITLE
Deej preventing windows from going to sleep

### ISSUE THREAD

**Issue by ericlindersson** [omriharel/deej#68] opened 2023-08-10 06:21 UTC
Hi,

I have issues putting PC to sleep.
When deej is on and usb is connected the computer goes to sleep but wakes up directly again.

**Comment by omriharel** [comment] 2023-08-10 09:42
Duplicate of #52, #21, #17 (potential solution in #52)

**Closed as not planned by omriharel** 2023-08-10 09:42 UTC
