### ISSUE TITLE
Deej prevents computer from sleeping?

### ISSUE THREAD

**Issue by Kickbut101** [omriharel/deej#17] opened 2020-10-23 04:47 UTC
I have since using Deej noticed my computer no longer stays asleep when I put it to sleep.

I originally thought it was my USB 3.0 controller (and in fact the hardware ID 1 was pointing to that) but have since resolved that. Now when I go to sleep I get a lastwake notification with an "Unknown" and the only way I get it to go away is if I unplug my deej arduino before sleep. Then my computer stays asleep just fine.

I assume the constant polling of the knobs/potentiometers sends signals back to the PC and keeps the computer from successfully staying asleep.

Any suggestions/advice?

**Comment by omriharel** [comment] 2020-10-23 08:40
Hey @Kickbut101, thanks for writing!

I'm looking into this. I think the best way that we could figure this out is by getting more inputs from our community of users (as I personally don't use sleep, at least not that I'm aware of). I went ahead and asked about this in our Discord server, and I'll update you as answers start coming in.

I'll also be on the lookout on my own PC, because I'm fairly sure it _does_ come back from sleep after it's been idle for a while.

Just to be sure we're on the same page, would you mind describing your current power settings and sleep scheme? What's your daily routine with regards to putting your computer to sleep? Do you do it manually or via a timer? The more details we have, the easier it might be to reproduce.

Thanks!

**Comment by Kickbut101** [comment] 2020-10-23 15:20
It's really easy to test. Just try putting your computer to sleep. If it _immediately_ comes back on you are experiencing the same issue I am.

Heres (probably) the part you care about in sleep settings;
![image](https://user-images.githubusercontent.com/16029826/97022098-4fac7500-1519-11eb-9622-7dcbfed9f0c5.png)


My routine is that I occasionally want to put my computer to sleep instead of shutting it down, I manually do it.

**Comment by omriharel** [comment] 2020-10-23 22:19
Hey @Kickbut101,

So I tried doing what you suggested, and put my PC to sleep while deej was running. It did not wake immediately. After a few minutes I woke it manually, and deej even continued to work as if the connection was never interrupted (which honestly surprised me).

I still can't rule out that this isn't an issue with deej, but it does appear to be at least somewhat hardware-related. I don't know if that helps, but I'm using the "Balanced" power plan on Windows. Also, I examined my settings compared to those you're showing and the only ones that I have set differently are "Put the computer to sleep: Never" and "Allow wake timers: Enable".

**Comment by omriharel** [comment] 2020-10-30 15:38
Hi again @Kickbut101, following our conversation in the project's Discord I'm going to close this since we haven't been able to isolate anything to a setup other than yours - if you come across any news on that front, please feel free to re-open this issue so we can continue following up on it.

Thanks!

**Closed by omriharel** 2020-10-30 15:38 UTC
